import { Major_Mono_Display, Raleway } from 'next/font/google';
import Head from 'next/head'
const majorMonoDisplay = Major_Mono_Display({
    subsets: ['latin'],
    variable: '--font-major_mono_display',
    weight: '400'
  })
  
  const raleway = Raleway({
    subsets: ['latin'],
    variable: '--font-raleway',
    weight: '100',
  })
export default function EventInfo() {
  return (
    <>
      <Head>
        <title>Event Info</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <div className='grid grid-cols-5 grid-row-1 w-full p-20'>
      <h1 className={`${majorMonoDisplay.variable} col-span-3 font-heading text-white text-8xl text-right`}>event info</h1>
    </div>
    {/*If you want it to be centered to the page and not off to the side*/}
    {/* <div className='flex w-full justify-center items-center'>
      <h1 className={`${majorMonoDisplay.variable} col-span-2 font-heading text-white text-7xl text-right `}>event info</h1>
    </div> */}
  <div className="grid w-full h-full grid-cols-7 items-center pt-6">
    <p className={`${raleway.variable} text-[#bac2b3] col-start-3 col-end-7 text-3xl`}> Lorem ipsum dolor sit amet consectetur adipisicing elit. Et amet porro odit debitis fuga reiciendis eligendi ea sunt adipisci earum quam culpa molestias saepe delectus totam a maiores, velit tenetur, vitae repellat sit incidunt sed nesciunt. Optio, voluptate modi. Tempora voluptates assumenda deleniti consequatur. Culpa minus tenetur repudiandae necessitatibus excepturi corrupti debitis assumenda porro nesciunt quae laudantium, esse, voluptas, harum consequuntur optio ea voluptates facilis aliquam inventore accusamus delectus. Possimus et molestias totam reiciendis nihil rerum rem eligendi officiis perferendis.</p>

  </div>


    </>
  )
}