import Head from 'next/head'
import { Inter } from 'next/font/google'
import { useState } from 'react'
import Layout from '@/components/Layout'
import data from "../public/data.json"
const inter = Inter({ subsets: ['latin'] })


export default function FAQ() {
  const [active, setActive] = useState([false, false, false, false, false]);
  const isSomeActive = active.some((element) => element);
  const handleClick = () => {
    isSomeActive
      ? setActive([false, false, false, false,false])
      : setActive([true, true, true, true, true, true]);
  };

  return (
    <>
      <Head>
        <title>FAQ</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='grid place-items-center w-full'>
      <Layout
        handleClick={handleClick}
        isSomeActive={isSomeActive}
        data={data}
        turn={active}
        setTurn={setActive}
      />
    </div>

    </>
  )
}
